import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
const server = spawn(process.execPath, ['scripts/serve.mjs'], { stdio: ['ignore', 'pipe', 'inherit'], windowsHide: true });
let browser;
try {
  await once(server.stdout, 'data');
  browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:4173');
  await page.waitForFunction(() => document.querySelector('#loading').style.display === 'none');
  await page.click('#flip-btn');
  await page.waitForSelector('.posting');
  assert.equal(await page.locator('#experience-type').inputValue(), 'nonvolunteer');
  assert.equal(await page.locator('.kind-badge').filter({ hasText: '자원봉사' }).count(), 0);
  assert.ok(await page.locator('.kind-badge').filter({ hasText: '인턴' }).count() > 0);
  const p = JSON.parse(await readFile('web/experience-results.json', 'utf8')).find(r => r.site.id === 'work24-youth').postings.find(p => p.userVisible);
  const title = await page.locator('.posting-title').first().textContent();
  await page.locator('.fav-btn').first().click();
  assert.equal(await page.locator('.fav-btn').first().getAttribute('aria-pressed'), 'true');
  await page.click('#favorites-btn');
  assert.equal(await page.locator('.posting').count(), 1);
  assert.ok((await page.locator('.posting-title').textContent()).includes(title.trim()));
  await page.click('#scheduler-btn');
  assert.ok(await page.locator('.cal-event').count() > 0);
  assert.equal(await page.locator('#show-posted').isChecked(), false);
  await mkdir('.test-artifacts', { recursive: true });
  await page.screenshot({ path: '.test-artifacts/scheduler.png', fullPage: true });
  // A missing source must not erase the user's saved copy.
  await page.route('**/experience-results.json', route => route.fulfill({ json: [] }));
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#loading').style.display === 'none');
  await page.click('#favorites-btn');
  assert.equal(await page.locator('.posting').count(), 1);
  assert.ok((await page.locator('.posting').textContent()).includes('저장 당시 사본 보존'));
  await page.unroute('**/experience-results.json');
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#loading').style.display === 'none');
  await page.click('#flip-btn');
  await page.screenshot({ path: '.test-artifacts/experience.png', fullPage: false, animations: 'disabled' });
  await page.selectOption('#record-kind', 'program_info');
  assert.ok(await page.locator('.posting').count() > 0);
  assert.ok((await page.locator('.posting-list').textContent()).includes('미래내일'));
  await page.screenshot({ path: '.test-artifacts/program-info.png', fullPage: false, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '.test-artifacts/mobile.png', fullPage: false, animations: 'disabled' });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  // Synthetic fixtures exist only in an isolated test browser, never in collected JSON.
  await page.evaluate(() => {
    const now = new Date();
    const future = new Date(now.getFullYear(), now.getMonth() + 1, 15);
    const date = `${future.getFullYear()}-${String(future.getMonth() + 1).padStart(2, '0')}-15`;
    const records = {};
    for (let i = 0; i < 5; i++) records[`fixture-${i}`] = { posting: { stableId: `fixture-${i}`, siteId: 'fixture', title: `달력 회귀 ${i}`, deadlineDate: i === 4 ? null : date, regDate: '2026-01-01', url: 'https://example.org' }, savedAt: new Date().toISOString() };
    localStorage.setItem('wf_favorites_v2', JSON.stringify({ version: 2, records, unresolved: [] }));
  });
  await page.reload();
  await page.waitForFunction(() => document.querySelector('#loading').style.display === 'none');
  await page.click('#scheduler-btn');
  const nextMonth = new Date(); nextMonth.setMonth(nextMonth.getMonth() + 1, 15);
  assert.equal(await page.locator('#cal-title').textContent(), `${nextMonth.getFullYear()}년 ${nextMonth.getMonth() + 1}월`);
  await page.locator('.cal-cell summary').click();
  assert.equal(await page.locator('.cal-cell details .cal-event:visible').count(), 1);
  assert.ok((await page.locator('#undated-favorites').textContent()).includes('달력 회귀 4'));
  assert.deepEqual(errors, []);
  console.log(`UI 통합 검증 통과: 비봉사 공고·사업 안내·즐겨찾기 저장/누락 보존·달력·모바일. 실제 공고 표본: ${p.title}`);
} finally { await browser?.close(); server.kill(); }
